### ISSUE TITLE
insert infura

### ISSUE THREAD

**Issue by henry-hz** [Andrew-Pohl/FUSE_KVM_Manager#1]
Hi Andy,
pls review
```
please input your infura Eth endpoint address (https://mainnet.infura.....): https://mainnet.infura.io/v3/6de10e1cd17b489b92bcaea47c229155
sed: -e expression #1, char 45: unknown option to `s'
```

**Comment by Andrew-Pohl** [comment]
Good spot Henry. fixed in a5e1cd8e2accddc71b29b7a258bd13d8dc0e840c. It was an issue with sed slash termination. Now just put the key in so  just "6de10e1cd17b489b92bcaea47c229155" that for you :)
